# Use an official Python runtime as the base image
FROM python:3.11-slim

# Set environment variables to prevent Python from buffering stdout and stderr
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN  pip install --upgrade pip

# Set the working directory in the container
WORKDIR /app

COPY . .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code

# Add a non-root user for security
RUN addgroup --system appgroup && adduser --system appuser --ingroup appgroup
RUN chown -R appuser:appgroup /app

# Switch to the non-root user
USER app

# Expose the port the app runs on
EXPOSE 80

# Define the default command to run the application
CMD ["python3", "app.py"]

