version: '3.8'  # Ensure you're using a compatible Docker Compose version

services:
  backend1:
    image: ajettesla/sdnprojectapp:1
    networks:
      - sdn_net

  backend2:
    image: ajettesla/sdnprojectapp:1
    networks:
      - sdn_net

  load_balancer:
    image: ajettesla/sdnprojectlb:2
    ports:
      - "5000:80"
    environment:
      BACKEND_SERVERS: "backend1:80|2,backend2:80|1"
    depends_on:
      - backend1
      - backend2
    networks:
      - sdn_net

networks:
  sdn_net:
    driver: bridge
