services:
  backend1:
    image: ajettesla/sdnprojectapp:2
    networks:
      - sdn_net

  backend2:
    image: ajettesla/sdnprojectapp:2
    networks:
      - sdn_net

  backend3:
    image: ajettesla/sdnprojectapp:2
    networks:
      - sdn_net

  load_balancer:
    image: ajettesla/sdnprojectlb:3
    ports:
      - "80:80"
    environment:
      BACKEND_SERVERS: "backend1:80|1,backend2:80|1,backend3:80|1"
      LOAD_SENSITIVITY: "true"
    depends_on:
      - backend1
      - backend2
      - backend3
    networks:
      - sdn_net

networks:
  sdn_net:
    driver: bridge
